site_name: hotio.dev
site_url: https://hotio.dev
site_author: hotio
site_description: Documentation for all Docker images maintained by hotio.
copyright: '&copy; 2026 hotio<br>Logos based on work by <a href="https://www.flaticon.com/authors/freepik" target="_blank" rel="noopener">Freepik</a> and <a href="https://freeicons.io/profile/6200" target="_blank" rel="noopener">Soni Sokell</a>'
repo_name: hotio
repo_url: https://github.com/hotio
edit_uri: 'website/edit/master/docs'
site_dir: .build
docs_dir: docs

extra:
  social:
  - icon: fontawesome/solid/heart
    link: '/#donations'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.gg/FycMN9gTC3'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/hotio'
    name: GitHub
  status:
    deprecated: This image is no longer receiving updates
    new: This image has recently been added

extra_css:
  - stylesheets/extra-13.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/tagcopy.js

theme:
  icon:
    repo: fontawesome/brands/github
    annotation: material/information
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - toc.follow
  language: en
  logo: img/hotio-circle.svg
  name: material
  palette:
    scheme: hotio
  custom_dir: overrides

markdown_extensions:
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - toc:
      permalink: true
  - admonition
  - abbr
  - pymdownx.blocks.caption
  - tables

nav:
- Home: index.md
- Containers:
  - Base:
    - containers/base.md
  - Apps:
    - containers/autoscan.md
    - containers/bazarr.md
    - containers/caddy.md
    - containers/cloudflareddns.md
    - containers/doplarr.md
    - containers/duplicacy.md
    - containers/jackett.md
    - containers/jellyfin.md
    - containers/lidarr.md
    - containers/mergerfs.md
    - containers/nzbget.md
    - containers/nzbhydra2.md
    - containers/overseerr.md
    - containers/plex.md
    - containers/prowlarr.md
    - containers/qbitmanage.md
    - containers/qbittorrent.md
    - containers/qui.md
    - containers/radarr.md
    - containers/requestrr.md
    - containers/rflood.md
    - containers/sabnzbd.md
    - containers/seerr.md
    - containers/slskd.md
    - containers/sonarr.md
    - containers/stash.md
    - containers/tautulli.md
    - containers/unpackerr.md
    - containers/whisparr.md
- Scripts:
  - scripts/sysinfo.md
  - scripts/pullio.md
  - scripts/arr-discord-notifier.md
- FAQ: faq.md
