copyright: Copyright &copy; 2021 hotio<br>Logos based on work by <a href="https://www.flaticon.com/authors/freepik">Freepik</a> from <a href="https://www.flaticon.com">flaticon.com</a> and <a href="https://freeicons.io/profile/6200">Soni Sokell</a> on <a href="https://freeicons.io">freeicons.io</a>
edit_uri: 'website/edit/master/docs'

extra:
  social:
  - icon: fontawesome/solid/heart
    link: 'https://hotio.dev/donate'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://hotio.dev/discord'
    name: Discord
  - icon: fontawesome/brands/docker
    link: 'https://hub.docker.com/u/hotio'
    name: Docker
  - icon: fontawesome/brands/github
    link: 'https://github.com/hotio'
    name: GitHub

  analytics:
    provider: google
    property: UA-126819406-1

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - redirects:
      redirect_maps:
        discord.md: 'https://discord.gg/3SnkuKp'
        dockerhub.md: 'https://hub.docker.com/u/hotio'
        ghcr.md: 'https://github.com/orgs/hotio/packages?ecosystem=container&visibility=public'
        quay.md: 'https://quay.io/user/hotio'
        github.md: 'https://github.com/hotio'
        donate.md: 'https://hotio.dev/#donations'

repo_name: hotio
repo_url: https://github.com/hotio
site_author: hotio
site_description: Documentation for all Docker images maintained by hotio.
site_name: hotio.dev
site_url: https://hotio.dev

theme:
  icon:
    repo: fontawesome/brands/github
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  language: en
  logo: img/hotio.svg
  name: material
  palette:
    scheme: hotio
  custom_dir: docs/overrides

markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - toc:
      permalink: true
  - admonition

nav:
- Home: index.md
- Containers:
  - Apps:
    - hotio/autoscan: containers/autoscan.md
    - hotio/bazarr: containers/bazarr.md
    - hotio/caddy: containers/caddy.md
    - hotio/cloudflareddns: containers/cloudflareddns.md
    - hotio/doplarr: containers/doplarr.md
    - hotio/duplicacy: containers/duplicacy.md
    - hotio/jackett: containers/jackett.md
    - hotio/jellyfin: containers/jellyfin.md
    - hotio/lidarr: containers/lidarr.md
    - hotio/nzbget: containers/nzbget.md
    - hotio/nzbhydra2: containers/nzbhydra2.md
    - hotio/overseerr: containers/overseerr.md
    - hotio/plex: containers/plex.md
    - hotio/prowlarr: containers/prowlarr.md
    - hotio/qbitmanage: containers/qbitmanage.md
    - hotio/qbittorrent: containers/qbittorrent.md
    - hotio/qflood: containers/qflood.md
    - hotio/radarr: containers/radarr.md
    - hotio/readarr: containers/readarr.md
    - hotio/rflood: containers/rflood.md
    - hotio/sabnzbd: containers/sabnzbd.md
    - hotio/sonarr: containers/sonarr.md
    - hotio/stash: containers/stash.md
    - hotio/tautulli: containers/tautulli.md
    - hotio/trackarr: containers/trackarr.md
    - hotio/unpackerr: containers/unpackerr.md
    - hotio/whisparr: containers/whisparr.md
  - Base Images:
    - hotio/base: containers/base.md
- Arr Discord Notifier: arr-discord-notifier.md
- Pullio: pullio.md
- FAQ: faq.md
- Support: /discord
- Donate: /donate
