copyright: Copyright &copy; 2020 hotio
edit_uri: ''

extra:
  social:
  - icon: fontawesome/brands/discord
    link: 'https://hotio.dev/discord'
    name: Discord
  - icon: fontawesome/brands/docker
    link: 'https://hub.docker.com/u/hotio'
    name: Docker
  - icon: fontawesome/brands/github
    link: 'https://github.com/docker-hotio'
    name: GitHub

extra_css:
  - stylesheets/extra.css

plugins:
- search
- redirects:
    redirect_maps:
      discord.md: 'https://discord.gg/3SnkuKp'
      docker.md: 'https://hub.docker.com/u/hotio'
      github.md: 'https://github.com/docker-hotio'
      discord-notification.sh.md: 'https://raw.githubusercontent.com/docker-hotio/.github/master/discord-notification.sh'

repo_name: hotio
repo_url: https://github.com/docker-hotio
site_author: hotio
site_description: Documentation to get the containers running
site_name: hotio.dev
site_url: https://hotio.dev

theme:
  favicon: img/favicon.ico
  features:
    - navigation.instant
  language: en
  logo: img/logo.png
  name: material
  palette:
    scheme: hotio
  custom_dir: docs/overrides

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
- Home: index.md
- Containers:
  - containers/apprise.md
  - containers/autoscan.md
  - containers/bazarr.md
  - containers/borg.md
  - containers/cloudflare-ddns.md
  - containers/crop.md
  - containers/hd-idle.md
  - containers/jackett.md
  - containers/jellyfin.md
  - containers/lidarr.md
  - containers/mergerfs.md
  - containers/mylar3.md
  - containers/nzbget.md
  - containers/nzbhydra2.md
  - containers/ombi.md
  - containers/plex.md
  - containers/plexarr.md
  - containers/radarr.md
  - containers/rar2fs.md
  - containers/rclone.md
  - containers/readarr.md
  - containers/requestrr.md
  - containers/restic.md
  - containers/sabnzbd.md
  - containers/scrutiny.md
  - containers/sonarr.md
  - containers/tautulli.md
  - containers/trackarr.md
  - containers/unpackerr.md
- Base Containers:
  - containers/base.md
  - containers/mono.md
